name: Hello

on:
  push:
    branches:
      - main

jobs:
  Hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run my action
        uses: ./
        with:
          name: 'This Dot Labs'
          ghToken: ${{ secrets.GITHUB_TOKEN }}
